# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Portfolio site deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  set_up_python:
    name: "Quality Check"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Get repo"
        uses: actions/checkout@v6

      - name: "Install Python"
        uses: actions/setup-python@v6

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: "Pylint Code"
        run: |
          pylint app.py

      - name: "Test with pytest"
        run: |
          pytest


      - name: "Deploy To Server"
        uses: easingthemes/ssh-deploy@main
        with:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PORTFOLIO_PRIVATE_KEY }}
            #ARGS: "-rlgoDzvc -i --delete"
            ARGS: "-rlgoDzvc -i"
            #SOURCE: ${{ secrets.SOURCE }}
            REMOTE_HOST: ${{ secrets.REMOTE_PORTFOLIO_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_PORTFOLIO_USER }}
            TARGET: ${{ secrets.REMOTE_PORTFOLIO_TARGET }}
            EXCLUDE: "/node_modules/"
            SCRIPT_AFTER: |
              whoami
              ls -al
              cd ${{ secrets.REMOTE_PORTFOLIO_TARGET }}
              source .venv/bin/activate
              # Kill any existing app.py process
              pkill -f app.py || echo "No app.py process found"
              # Navigate to app directory
              # Start app.py in background with nohup
              nohup python3 app.py > app.log 2>&1 &
              # Confirm it is running
              ps aux | grep '[a]pp.py'